name: newrelic-integration-e2e-action
description: Run e2e tests for the newrelic integrations.
inputs:
  spec_path:
    description: Path to the test specification file.
    required: false
    default: "e2e/spec.yml"
  integration_pkg:
    description: Relative path to the pkg to be tested
    required: true
  license_key:
    description: New Relic license key used to test the integration
    required: true

runs:
  using: "composite"
  steps:
    - id: spec-validator
      run: make -C ${{ github.action_path }}/spec-validator SPEC_PATH=${{ github.workspace }}/${{ inputs.spec_path }}
      shell: bash
    - run: echo "${{ inputs.license_key }}"
      shell: bash
    - run: echo "$SECRET_DEMO"
      shell: bash
