name: newrelic-integration-e2e-action
description: Run e2e tests for the newrelic integrations.
inputs:
  spec:
    description: Path to the specification files for the tests. Regular expressions are supported.
    required: false
    default: "e2e/spec-*.yml"
  integration_pkg:
    description: Relative path to the pkg to be tested
    required: true
  license_key:
    description: New Relic license key used to test the integration
    required: true

runs:
  using: "composite"
  steps:
    - run: ls .github
      shell: bash
    - run: pwd
      shell: bash
    - id: build-spec-validator
      run: docker build -t newrelic-integration-e2e-action:spec-validator  spec-validator
      shell: bash
    - id: run-spec-validator
      run: docker run newrelic-integration-e2e-action:spec-validator
      shell: bash
    - run: echo "${{ inputs.license_key }}"
      shell: bash
    - run: echo "$SECRET_DEMO"
      shell: bash
