name: newrelic-integration-e2e-action
description: Run e2e tests for the newrelic integrations.
inputs:
  spec_path:
    description: Path to the test specification file.
    required: true
  license_key:
    description: New Relic license key used to test the integration
    required: true
  verbose:
    description: Verbose mode enabled
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - id: run-spec
      run: go run ${{ github.action_path }}/newrelic-integration-e2e/main.go --agent_dir=agent_dir --license_key=${{ inputs.license_key }} --root_dir=${{ github.workspace }} --spec_path=${{ github.workspace }}/${{ inputs.spec_path }} --verbose_mode=${{ inputs.verbose }}
      #run: make -C ${{ github.action_path }}/newrelic-integration-e2e ROOT_DIR=${{ github.action_path }} LICENSE_KEY=${{ inputs.license_key }} SPEC_PATH=${{ github.workspace }}/${{ inputs.spec_path }} VERBOSE=${{ inputs.verbose }} run
      shell: bash



